#!/usr/bin/env bash
# scripts/hooks/pre-commit.d/20-backlog-freshness.sh
#
# Pre-commit check — .planning/BACKLOG.md aggregate freshness gate (2026-07-13).
#
# A resident dispatcher leaf (mirrors 20-index-freshness.sh; the dispatcher runs
# every executable pre-commit.d/* in glob order and needs NO edit — do NOT run
# install-hooks.sh, the .git/hooks/pre-commit symlink already points at the
# dispatcher).
#
# WHAT IT GATES: .planning/BACKLOG.md is a DERIVED aggregate of .planning/backlog/
# briefs, regenerated by backlog-regen.cjs (skills repo; provisioned at
# ~/.claude/dhx-tools/backlog-regen.cjs). Every scripted BRIEF committer (backlog-
# close / capture / reopen / promote-next) already regenerates it and carries it in
# its own scoped pathspec — the committer-adaptation half of the zero-touch story.
# The actionable-lifecycle committers that mutate reports/skills/*/actionable/ (the
# defect-row input — membership AND in-place status) carry it too since 2026-09-12,
# on the commit's own basis, and a staged actionable/ change triggers this gate — see
# ~/repos/skills/docs/decisions/2026-09-12-backlog-freshness-gate-triggers-on-actionable-changes.md
# The uncovered residue is AD-HOC brief commits (observed 2026-07-12: a manually-
# shipped brief left the aggregate stale a full day, hiding it from navigation).
# This leaf makes that drift UNCOMMITTABLE, with the exact fix in the block message.
#
# DESIGN — staged-view DELTA-check, auto-CHECK never auto-regen:
#   The initiating prompt (cross-repo:docs/prompts/done/2026-07-13-backlog-autoregen-
#   precommit-hook-prompt.md) proposed an auto-regen + `git add` leaf; that design is
#   REJECTED on the trap-table §8 evidence
#   (cross-repo:docs/research/2026-07-10-shell-git-os-gotchas.md):
#   a pre-commit `git add` during a scoped `git commit -- <paths>` leaks the blob
#   into the commit AND resets the real index underneath — three-way `MM` corruption
#   on the repo's dominant commit shape. Decision record:
#   cross-repo:docs/decisions.md § "BACKLOG.md freshness gate" (2026-07-13).
#
#   Like the index gate, this leaf materializes the STAGED tree and regenerates the
#   aggregate there, so only content THIS commit stages is judged; and it blocks only
#   drift THIS commit CAUSES (staged-tree ideal ≠ HEAD-tree ideal), never drift merely
#   inherited from a peer's un-regenerated HEAD — .planning/backlog/ is the highest-
#   concurrency path on the shared tree, so the delta refinement is load-bearing here,
#   not gold-plating.
#
#   backlog-regen.cjs reads (all under the given root): .planning/backlog/*.md rows,
#   .planning/backlog/{shipped,rejected,superseded}/ footer counts, milestone
#   vocabulary from .planning/{MILESTONES,ROADMAP,STATE}.md, and defect rows from
#   reports/skills/*/actionable/. ALL of those are materialized (MATERIALIZE_PATHS)
#   so the staged-view generation is the true post-commit ideal — if the generator
#   ever grows a new input surface, add it there (the failure mode is a LOUD false
#   block, not silent drift). Generation runs in --emit mode (side-effect-free,
#   stdout; shipped skills-side 2026-07-13): git-free fs walks over the bare
#   materialized tree, which is tracked-only by construction — an untracked/
#   gitignored draft brief never enters the staged-view generation. As of the
#   skills-side tracked-set read (2026-07-14) a hand-run working-tree regen ALSO
#   enumerates via `git ls-files`, so an untracked draft no longer enters THAT
#   aggregate either: the two views converge on membership, and the section-A
#   diagnosis note below flags only unstaged CONTENT edits to tracked files (still
#   divergent — a regen reads working-tree bytes, the gate reads staged blobs; the
#   candidate fix in REMEDY below sidesteps the regen entirely). --emit is also
#   the H1 closure (drain review 2026-07-13): it NEVER creates a field-review-candidate
#   brief and NEVER emits the would-created row; and the tracked-set read closes the
#   WRITE side too (the candidate brief the write regen creates is untracked → never
#   rowed in), so the field-review threshold no longer wedges on a dangling
#   candidate row.
#
#   The `Last updated: <date>` header stamp is NORMALIZED out of every generated-vs-
#   blob comparison — a date-only difference is not drift (else any brief-touching
#   commit on a later day than the last regen would false-block on identical rows).
#
# REMEDY — the persisted CANDIDATE (2026-08-23; skills DEC-2026-08-23-freshness-gate-
# remedy-is-the-defect-not-the-invariant): on a BLOCK, the post-commit ideal this
# leaf just generated (GEN_STAGED — the exactly-correct aggregate for THIS commit's
# scoped view) is PERSISTED to an untracked, pid-suffixed file under the real gitdir
# (it survives the EXIT trap and can never be swept into a commit), and the printed
# fix is ONE operator-run command: install the candidate over the aggregate, stage
# it, and retry the ORIGINAL commit (message + pathspec recovered from the invoking
# `git commit`'s /proc cmdline; when unrecoverable, the fix says to re-run it
# verbatim). The OLD printed fix (a working-tree regen) was NON-CONVERGENT under
# peer divergence: the regen reads the REAL index (a peer's staged brief included),
# this gate reads the commit's scoped view, so the regen re-introduced the peer's
# row and the block never cleared (measured: 17-103 turns per wedged incident).
# The hook itself still NEVER stages and NEVER mutates any index — only the
# operator-run printed command stages (the auto-git-add rejection above binds
# unchanged) — and block/allow polarity is UNCHANGED: peer-divergence detection
# selects remediation TEXT only, it never flips block to warn.
# RECORDED SIDE EFFECT (adjudicated, accepted under the token objective): on an
# UNSCOPED commit while a peer's brief is staged in the real index, the commit's
# index view INCLUDES that brief, so the candidate carries its row before the peer
# lands — a dangling aggregate row until they do. Self-heals at the next scripted
# regen.
#
# TRIGGER SCOPING (load-bearing): fires ONLY when the commit stages a path under
# .planning/backlog/ (terminal subdirs INCLUDED — a `git mv` to shipped/ must drop
# the row and bump the footer count), a reports/skills/*/actionable/*.md (an add, a
# delete — an archive move decomposes into D+A — or an edit; only an edit that changes
# the file's Defects row — status, title/H1, created_at, skill — can block), or
# .planning/BACKLOG.md itself (superset trigger: a hand-edited aggregate staged alone is
# verified). Hook-less paths are NOT gated: cherry-pick, revert and rebase run no
# pre-commit hook, so a row change they carry lands unverified. No --diff-filter
# (a staged `git rm` of a brief leaves a dangling row, so deletions must trigger);
# --no-renames (a move decomposes into D+A). DELIBERATE EXCLUSIONS — two path
# classes, excluded for DIFFERENT reasons; do not read one rationale as covering
# both. (1) The vocabulary files (ROADMAP/STATE/MILESTONES): STATE.md is touched by
# every GSD phase op whose committers (gsd-tools) do not carry BACKLOG.md, so
# triggering there would wedge GSD flows. (2) reports/skills/*/telemetry/ and
# */archive/: they feed no row. reports/skills/*/actionable/ is NOT excluded — it
# was, on cost (~6-7 non-carrying chore commits a day), until the 2026-09-12
# committer migration made every scripted actionable committer carry the aggregate;
# of the 6 actionable/archive commits measured after it, the only 3 without the
# aggregate were an unmigrated fence. So the trigger is now the backstop that catches
# the NEXT writer that skips it (a hand commit pays the printed one-command fix below).
# A commit that changes no row still passes — only caused drift blocks. Auto-regen
# inside this leaf stays REJECTED (see DESIGN above).
#
# Fail-mode (mirrors the sibling leaves, D-06 — polarity depends on WHEN it fails):
#   - node absent, regen tool unresolvable, regen exits non-zero over the staged
#     tree, or mktemp fails                       -> exit 0 (fail-OPEN; no drift
#     determined yet — a repo without the toolchain must never be bricked).
#   - staged-tree materialization fails           -> exit 1 (fail-CLOSED; an
#     incomplete staged tree would report SPURIOUS drift).
#   - HEAD-side work fails DURING drift resolution -> exit 1 (fail-CLOSED; drift
#     exists and caused-vs-inherited cannot be decided).
#   - caused drift                                 -> exit 1 (fail-CLOSED).
#
# Escape hatch: `git commit --no-verify`.

set -uo pipefail

# ── ARM STATE ────────────────────────────────────────────────────────────────
# ARMED at land (2026-07-13) — the scripted committers already regen + carry the
# aggregate, so arming adds no friction to any adapted path. In-file (not perms:
# install-hooks.sh blanket-chmod-+x's pre-commit.d/*, silently re-arming a chmod -x
# leaf). Env override for probes / emergency disarm.
[ "${BACKLOG_FRESHNESS_GATE_ARMED:-1}" = 1 ] || exit 0

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
cd "$REPO_ROOT" || exit 0

# --- Trigger scoping ----------------------------------------------------------
# Pure git+bash before any node startup — this runs on EVERY commit in the repo.
mapfile -d '' -t staged < <(git diff -z --cached --name-only --no-renames -- \
  .planning/backlog/ .planning/BACKLOG.md reports/skills/)

triggered=0
for p in "${staged[@]}"; do
  case "$p" in
    # `*` in a case glob spans `/`, so terminal subdirs are covered.
    .planning/BACKLOG.md|.planning/backlog/*.md) triggered=1; break ;;
    # An actionable/ add, delete or row-changing edit changes a Defects row; telemetry/
    # and archive/ feed none (an archive MOVE still triggers via its actionable/ D half).
    reports/skills/*/actionable/*.md) triggered=1; break ;;
  esac
done
[ "$triggered" = 0 ] && exit 0

# Only keep an aggregate fresh if the repo CARRIES one (present in the commit's
# index view). Absent means the aggregate convention isn't adopted here — or this
# commit removes it — so no-op (mirrors the index gate's carrier check).
git cat-file -e :.planning/BACKLOG.md 2>/dev/null || exit 0

# --- Resolve the generator (fail-OPEN at every miss) ----------------------------
# BACKLOG_FRESHNESS_REGEN, when set, is EXCLUSIVE (no fallback) — deterministic
# probe legs. Default: repo-local (the skills repo carries the canonical script),
# then the machine-global dhx-tools symlink (every other fleet repo).
if [ -n "${BACKLOG_FRESHNESS_REGEN:-}" ]; then
  REGEN="$BACKLOG_FRESHNESS_REGEN"
elif [ -f "$REPO_ROOT/scripts/backlog-regen.cjs" ]; then
  REGEN="$REPO_ROOT/scripts/backlog-regen.cjs"
else
  REGEN="$HOME/.claude/dhx-tools/backlog-regen.cjs"
fi
[ -f "$REGEN" ] || {
  echo "pre-commit: backlog-regen.cjs not resolvable — skipping BACKLOG.md freshness check." >&2
  exit 0   # fail-OPEN: tool absent (D-06)
}
command -v node >/dev/null 2>&1 || {
  echo "pre-commit: node not found — skipping BACKLOG.md freshness check." >&2
  exit 0   # fail-OPEN: toolchain absent (D-06)
}

# --- Materialize the staged tree ------------------------------------------------
# Everything backlog-regen.cjs reads under a root (see DESIGN above). Bulk
# checkout-index (one process); `git ls-files` reads the commit's index view, so a
# staged-ADDED brief is present and a staged-DELETED one is already absent.
# `git stash` is NOT used (refs/stash is shared across worktrees on the shared tree).
MATERIALIZE_PATHS=(.planning/backlog/ .planning/BACKLOG.md
  .planning/MILESTONES.md .planning/ROADMAP.md .planning/STATE.md
  reports/skills/)

STAGED_TREE="$(mktemp -d)" || exit 0   # fail-OPEN: cannot make temp dir (D-06)
HEAD_TREE=""                            # materialized lazily on first drift (delta-check)
trap 'rm -rf "$STAGED_TREE" "$HEAD_TREE"' EXIT

# fail-CLOSED on a materialization failure: an incomplete staged tree would make the
# generator report SPURIOUS drift. pipefail propagates either side of the pipe.
if ! git ls-files -z -- "${MATERIALIZE_PATHS[@]}" \
     | git checkout-index -z --stdin --prefix="$STAGED_TREE/"; then
  echo "pre-commit: could not materialize the staged tree for the BACKLOG.md freshness check — blocking." >&2
  echo "  (bypass once with: git commit --no-verify)" >&2
  exit 1
fi

# Set the staged aggregate blob aside (doubles as the materialized-carrier check —
# --emit never writes into the tree, so this is bookkeeping, not overwrite-protection).
mv "$STAGED_TREE/.planning/BACKLOG.md" "$STAGED_TREE/.blob-staged" 2>/dev/null || {
  echo "pre-commit: staged .planning/BACKLOG.md missing from the materialized tree — blocking." >&2
  echo "  (bypass once with: git commit --no-verify)" >&2
  exit 1
}

# --- Generate over the staged tree (fail-OPEN on generator failure) -------------
# --emit: side-effect-free — prints the ideal aggregate to stdout, creates NOTHING
# (no BACKLOG.md write, no field-review-candidate brief; H1 — see DESIGN above).
GEN_STAGED="$STAGED_TREE/.gen-staged"            # the post-commit ideal aggregate
if ! node "$REGEN" --emit "$STAGED_TREE" >"$GEN_STAGED" 2>/dev/null; then
  echo "pre-commit: backlog-regen.cjs --emit failed over the staged tree — skipping BACKLOG.md freshness check." >&2
  exit 0   # fail-OPEN: no drift determined (the generator, not the commit, is broken)
fi

# norm_cmp — compare two aggregate files with the `Last updated:` header stamp
# normalized out (a date-only difference is not drift). Byte-exact otherwise
# (file streams via process substitution — no `$()` trailing-newline stripping).
norm_cmp() {   # $1, $2 = files; returns 0 when equal modulo the date stamp
  cmp -s <(sed '/^<!-- Regenerated by .*Last updated: /d' "$1") \
         <(sed '/^<!-- Regenerated by .*Last updated: /d' "$2")
}

# Fast path: the committed aggregate already matches the post-commit ideal.
norm_cmp "$GEN_STAGED" "$STAGED_TREE/.blob-staged" && exit 0

# --- Drift exists — CAUSED by this commit, or inherited from HEAD? ---------------
# Inherited-allow needs BOTH clauses (mirrors the index gate's F2 guard):
#   staged_gen == head_gen   (this commit does not change the ideal aggregate)
#   staged_blob == head_blob (this commit does not change the committed blob — raw cmp)
# HEAD-side failure during resolution -> fail-CLOSED (drift established, caused-vs-
# inherited undecidable). A HEAD without the aggregate (first-adoption commit) has
# nothing to inherit from -> treat as caused.
inherited_allow() {
  [ -n "$HEAD_TREE" ] && return 1                       # only called once
  local head_idx
  HEAD_TREE="$(mktemp -d)" || { HEAD_TREE=""; return 1; }
  head_idx="$(mktemp)" || { rm -rf "$HEAD_TREE"; HEAD_TREE=""; return 1; }
  if ! GIT_INDEX_FILE="$head_idx" git read-tree HEAD 2>/dev/null \
     || ! GIT_INDEX_FILE="$head_idx" git ls-files -z -- "${MATERIALIZE_PATHS[@]}" 2>/dev/null \
            | GIT_INDEX_FILE="$head_idx" git checkout-index -z --stdin --prefix="$HEAD_TREE/" 2>/dev/null; then
    rm -f "$head_idx"; return 1
  fi
  rm -f "$head_idx"
  [ -f "$HEAD_TREE/.planning/BACKLOG.md" ] || return 1  # first adoption — caused by definition
  mv "$HEAD_TREE/.planning/BACKLOG.md" "$HEAD_TREE/.blob-head" || return 1
  node "$REGEN" --emit "$HEAD_TREE" >"$HEAD_TREE/.gen-head" 2>/dev/null || return 1
  norm_cmp "$GEN_STAGED" "$HEAD_TREE/.gen-head" \
    && cmp -s "$STAGED_TREE/.blob-staged" "$HEAD_TREE/.blob-head"
}

inherited_allow && exit 0

# --- BLOCK: caused drift (or HEAD-side resolution failed) ------------------------
# emit_capped_diff — bounded old->new diff so a block never dumps thousands of tokens.
emit_capped_diff() {   # $1 = old file, $2 = new file
  local d n
  d="$(diff "$1" "$2" 2>/dev/null | grep '^[<>]' || true)"
  n="$(printf '%s\n' "$d" | grep -c '^[<>]' || true)"
  printf '%s\n' "$d" | head -20 | sed 's/^< /  - /; s/^> /  + /'
  [ "${n:-0}" -gt 20 ] && echo "  … and $((n - 20)) more differing lines (run the regen to see all)."
}

# --- Persist the candidate (see REMEDY in the header) ---------------------------
# GEN_STAGED *is* the correct post-commit aggregate for this commit's scoped view.
# Copy it out of the trap-cleaned temp tree to an untracked pid+time-suffixed path
# under the real gitdir (never inside the worktree, so it can never be swept into a
# commit). The per-block unique name means a printed fix can never clobber a NEWER
# candidate — each block's command names its own file. Stale candidates are pruned
# after a day (best-effort). The hook NEVER stages and NEVER mutates any index.
CANDIDATE=""
GITDIR="$(git rev-parse --absolute-git-dir 2>/dev/null)"
if [ -n "$GITDIR" ] && [ -d "$GITDIR" ]; then
  find "$GITDIR" -maxdepth 1 -name 'backlog-freshness-candidate.*' -mmin +1440 -delete 2>/dev/null || true
  _cand="$GITDIR/backlog-freshness-candidate.$$.$(date +%s 2>/dev/null || echo 0).md"
  cp "$GEN_STAGED" "$_cand" 2>/dev/null && CANDIDATE="$_cand"
fi

# recover_commit_cmd — walk up /proc ancestry to the invoking `git commit` and print
# it shell-quoted, so the fix can retry the ORIGINAL commit (same message, same
# pathspec). The leaf usually runs git -> dispatcher -> leaf, but the depth is not
# contractual, so walk up to 6 ancestors. A scoped pathspec (a `--` section) that
# omits .planning/BACKLOG.md gets it APPENDED — a scoped retry whose pathspec omits
# the aggregate would re-block, because the commit view would keep HEAD's stale
# blob. Best-effort: returns 1 when no `git commit` ancestor exists (e.g. a probe
# driving the leaf directly); the printed fix then says to re-run the original
# commit command verbatim.
recover_commit_cmd() {
  local pid=$$ i a out seen_commit seen_dashdash has_agg
  local -a args
  for i in 1 2 3 4 5 6; do
    pid="$(sed 's/^.*) //' "/proc/$pid/stat" 2>/dev/null | awk '{print $2}')"
    [ -n "$pid" ] && [ "$pid" -gt 1 ] 2>/dev/null || return 1
    [ -r "/proc/$pid/cmdline" ] || continue
    args=()
    mapfile -d '' -t args < "/proc/$pid/cmdline" 2>/dev/null
    [ "${#args[@]}" -ge 2 ] || continue
    case "${args[0]##*/}" in git) ;; *) continue ;; esac
    seen_commit=0; seen_dashdash=0; has_agg=0
    for a in "${args[@]:1}"; do
      [ "$a" = commit ] && seen_commit=1
      [ "$a" = -- ] && seen_dashdash=1
      [ "$seen_dashdash" = 1 ] && [ "$a" = .planning/BACKLOG.md ] && has_agg=1
    done
    [ "$seen_commit" = 1 ] || continue
    out=""
    for a in "${args[@]}"; do out+="$(printf '%q' "$a") "; done
    out="${out% }"
    [ "$seen_dashdash" = 1 ] && [ "$has_agg" = 0 ] && out+=" .planning/BACKLOG.md"
    printf '%s' "$out"
    return 0
  done
  return 1
}

{
  echo "pre-commit: .planning/BACKLOG.md would be stale after this commit — regenerate before committing."
  emit_capped_diff "$STAGED_TREE/.blob-staged" "$GEN_STAGED"
  if [ -n "$CANDIDATE" ]; then
    if ORIG_CMD="$(recover_commit_cmd)"; then
      echo "  fix (ONE command — the gate already computed the correct post-commit aggregate and"
      echo "       saved it as an untracked candidate; this installs it, stages it, and retries"
      echo "       your original commit with its message and pathspec):"
      echo "    cp $(printf '%q' "$CANDIDATE") $(printf '%q' "$REPO_ROOT/.planning/BACKLOG.md") && git -C $(printf '%q' "$REPO_ROOT") add .planning/BACKLOG.md && $ORIG_CMD"
    else
      echo "  fix: the gate saved the correct post-commit aggregate as an untracked candidate. Run:"
      echo "    cp $(printf '%q' "$CANDIDATE") $(printf '%q' "$REPO_ROOT/.planning/BACKLOG.md") && git -C $(printf '%q' "$REPO_ROOT") add .planning/BACKLOG.md"
      echo "       then re-run your ORIGINAL git commit command verbatim (same message, same"
      echo "       pathspec — a SCOPED commit must keep .planning/BACKLOG.md IN the pathspec:"
      echo "        git commit -- <your-paths> .planning/BACKLOG.md)"
    fi
  else
    echo "  fix: node $REGEN && git add .planning/BACKLOG.md"
    echo "       (SCOPED commit? .planning/BACKLOG.md must be IN the pathspec, not merely staged:"
    echo "        git commit -- <your-paths> .planning/BACKLOG.md)"
  fi
} >&2

# Self-diagnose the shared-tree divergences that made the OLD (working-tree regen)
# remedy loop (mirrors the index gate's two notes). Diagnosis-only — never changes
# block/allow; with the candidate fix above these shapes no longer wedge, so the
# notes now warn AGAINST a hand regen instead of prescribing peer-touching exits.
feeding_paths=(.planning/backlog/ .planning/BACKLOG.md
  .planning/MILESTONES.md .planning/ROADMAP.md .planning/STATE.md reports/skills/)

# (A) unstaged working-tree EDITS to tracked feeding files — a hand-run working-tree
# regen reads their working-tree CONTENT while this gate reads staged blobs, so a
# manual `node backlog-regen.cjs && git add` can diverge and re-block. Untracked
# DRAFTS no longer diverge: since 2026-07-14 backlog-regen enumerates via
# `git ls-files`, excluding an untracked draft exactly as this staged view does.
divergent="$(git diff --name-only -- "${feeding_paths[@]}" 2>/dev/null || true)"
if [ -n "$divergent" ]; then
  {
    echo "  note: the tracked files below have UNSTAGED working-tree edits. A hand-run"
    echo "        working-tree regen would read that content and diverge from this staged-view"
    echo "        check — use the candidate fix above (it converges); do not regen by hand."
    printf '%s\n' "$divergent" | sed 's/^/          /'
  } >&2
fi

# (B) peer staged-only divergence — paths staged in the REAL index but outside this
# (scoped) commit's temp pathspec view. --absolute-git-dir resolves the real index
# for the primary AND a worktree, unaffected by the temp-index GIT_INDEX_FILE.
real_index="$(git rev-parse --absolute-git-dir 2>/dev/null)/index"
real_staged="$(GIT_INDEX_FILE="$real_index" git diff --cached --name-only -- "${feeding_paths[@]}" 2>/dev/null || true)"
this_commit_staged="$(git diff --cached --name-only -- "${feeding_paths[@]}" 2>/dev/null || true)"
peer_staged="$(comm -23 \
  <(printf '%s\n' "$real_staged"        | sed '/^$/d' | sort -u) \
  <(printf '%s\n' "$this_commit_staged" | sed '/^$/d' | sort -u) 2>/dev/null || true)"
if [ -n "$peer_staged" ]; then
  {
    echo "  note: the aggregate-feeding paths below are STAGED in the real index but OUTSIDE"
    echo "        this (scoped) commit — a peer session's separately-staged work. A hand-run"
    echo "        regen would re-introduce their rows and re-block forever; the candidate fix"
    echo "        above is computed over THIS commit's view and converges. Leave the peer's"
    echo "        paths alone."
    printf '%s\n' "$peer_staged" | sed 's/^/          /'
  } >&2
fi

exit 1
